
[functions.send-telegram-log]
enabled = true
verify_jwt = true
import_map = "./functions/send-telegram-log/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-telegram-log/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-telegram-log/*.html" ]

[functions.send-telegram-broadcast]
enabled = true
verify_jwt = true
import_map = "./functions/send-telegram-broadcast/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-telegram-broadcast/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-telegram-broadcast/*.html" ]
